import { NextRequest, NextResponse } from "next/server";
import { Resend } from "resend";

const AUDIENCE_ID = process.env.RESEND_AUDIENCE_GATE ?? process.env.RESEND_AUDIENCE_GENERAL;
const FROM = "3vo Agents <noreply@3vo.ai>";
const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL ?? "https://prompts.3vo.ai";

export async function POST(req: NextRequest) {
  let email: string;
  let agent: string | undefined;

  try {
    const body = await req.json();
    email = body?.email?.trim?.() ?? "";
    agent = body?.agent;
  } catch {
    return NextResponse.json({ error: "Invalid body" }, { status: 400 });
  }

  if (!email || !email.includes("@")) {
    return NextResponse.json({ error: "Invalid email" }, { status: 400 });
  }

  const key = process.env.RESEND_API_KEY;
  if (!key) {
    // Accept silently so the UI flow works in dev
    return NextResponse.json({ ok: true, skipped: true });
  }

  const resend = new Resend(key);

  if (AUDIENCE_ID) {
    try {
      await resend.contacts.create({ audienceId: AUDIENCE_ID, email, unsubscribed: false });
    } catch {
      // contact may already exist — non-fatal
    }
  }

  const rawAgent = typeof agent === "string"
    ? agent.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase()).slice(0, 100)
    : "our agents";
  const agentLabel = rawAgent
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#x27;");

  try {
    await resend.emails.send({
      from: FROM,
      to: [email],
      subject: "You ran out of free runs — here's a deal",
      html: `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="background:#0A0A0A;color:#E8E8E8;font-family:monospace;padding:40px 24px;max-width:520px;margin:0 auto;">
  <p style="color:#00FF85;font-size:11px;letter-spacing:3px;text-transform:uppercase;margin-bottom:24px;">PROMPTS.3VO.AI</p>
  <h1 style="font-size:22px;font-weight:900;margin-bottom:16px;line-height:1.2;">
    You tried ${agentLabel}.<br>Now finish the job.
  </h1>
  <p style="color:rgba(232,232,232,0.6);font-size:14px;line-height:1.6;margin-bottom:24px;">
    You used all 3 free runs. The output you saw was generated by a 3-step AI chain — not a template. If it got you close, imagine what unlimited runs could do.
  </p>
  <a href="${BASE_URL}/api/checkout"
     style="display:inline-block;background:#00FF85;color:#0A0A0A;font-weight:700;font-size:11px;letter-spacing:3px;text-transform:uppercase;padding:14px 28px;text-decoration:none;">
    UPGRADE FOR $19/MO →
  </a>
  <p style="color:rgba(232,232,232,0.25);font-size:11px;margin-top:32px;letter-spacing:1px;">
    No contracts. Cancel anytime. All 5 agents, unlimited runs.
  </p>
  <p style="color:rgba(232,232,232,0.15);font-size:10px;margin-top:16px;">
    You're receiving this because you entered your email at prompts.3vo.ai.
    <a href="{{unsubscribe_url}}" style="color:rgba(232,232,232,0.3);">Unsubscribe</a>
  </p>
</body>
</html>`,
    });
  } catch (err) {
    console.error("[gate-capture] email send error:", err);
    // Non-fatal — contact was already captured in audience
  }

  return NextResponse.json({ ok: true });
}
